stdout="Colored"
level_filter="Info"
#log_file="log/log.txt"

module_levels = [
    ["debug_collision","Info"],

    ["resource::animation" ,"Trace"],

    ["amethyst_collision::system::detect_contact" ,"Info"],

    ["fight_game" ,"Info"],
#    ["fight_game::load" ,"Info"],
    ["fight_game::input" ,"Error"],
#    ["fight_game::system::debug::command" ,"Debug"],
    ["fight_game::system::extrude" ,"Info"],
    ["fight_game::components::collision" ,"Error"],
    ["fight_game::paramater::translate_animation" ,"Debug"],

    ["sync_position_to_world" ,"Error"],
    ["gfx_backend_vulkan" ,"Warn"],
    ["input_handle::system", "Error"],

    ["amethyst_sprite_studio::system::build_nodes", "Warn"],
    ["amethyst_sprite_studio::resource", "Debug"],
    ["amethyst_sprite_studio::renderer", "Error"],

    ["movement_transform::system", "Info"],

    #["command_parser::command", "trace"]
]